package:
  name: "HGTCoGene"
  version: "0.1"

source:
  git_url: "https://github.com/clinte14/GeneCoOccurrence.git"
  sha256: 7cbedb69afac6859154e2f621a03785993a377825abf5a433d857f0f9872d91e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pandas
    - matplotlib-base
    - seaborne
    - graphviz
    - networkx
    - pyvis


test:
  imports:

about:
  home: "https://github.com/clinte14/GeneCoOccurrence"
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: GNU
  summary: "A tool for exploring relationships within small sets of unclassified microbial genes."
  doc_url: https://github.com/clinte14/GeneCoOccurrence#readme
  dev_url: https://github.com/clinte14

extra:
  recipe-maintainers:
    - clinte14
